server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'routes'
#zuul:
#  routes:
#    user-serivce:
#      path: /userService/**
#    feign-service:
#      path: /feignService/**

#zuul:
#  ignored-services: user-service,feign-service #关闭默认路由配置

#zuul:
#  prefix: /proxy #给网关路由添加前缀

#zuul:
#  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤

#zuul:
#  add-host-header: true #设置为true重定向是会添加host请求头

